"""
nullable explanation

Revision ID: 28e5c5539122
Revises: e1b118af820c
Create Date: 2026-03-29 11:27:54.566318

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "28e5c5539122"
down_revision: str | Sequence[str] | None = "e1b118af820c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("exercises", "explanation",
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
    # Заменяем пустые строки на NULL после того как поле стало nullable
    op.execute("UPDATE exercises SET explanation = NULL WHERE explanation = ''")


def downgrade() -> None:
    """Downgrade schema."""
    # Заменяем NULL на пустую строку перед тем как сделать поле NOT NULL
    op.execute("UPDATE exercises SET explanation = '' WHERE explanation IS NULL")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("exercises", "explanation",
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
