"""
enhance answers

Revision ID: 311e459e8905
Revises: 380cb327560e
Create Date: 2026-02-07 20:22:11.870933

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "311e459e8905"
down_revision: str | Sequence[str] | None = "380cb327560e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_current_exercises",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["exercise_id"], ["exercises.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "exercise_id"),
    )
    op.add_column("user_answers", sa.Column("solve_time", sa.Integer(), nullable=False))
    op.drop_constraint(op.f("users_current_exercise_id_fkey"), "users", type_="foreignkey")
    op.drop_column("users", "current_exercise_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("current_exercise_id", sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f("users_current_exercise_id_fkey"), "users", "exercises", ["current_exercise_id"], ["id"])
    op.drop_column("user_answers", "solve_time")
    op.drop_table("user_current_exercises")
    # ### end Alembic commands ###
