"""
init

Revision ID: 380cb327560e
Revises:
Create Date: 2026-02-07 11:37:28.751002

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "380cb327560e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("handler_type", sa.String(length=32), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["categories.id"] ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)
    op.create_index(op.f("ix_categories_parent_id"), "categories", ["parent_id"], unique=False)
    op.create_table(
        "exercises",
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=True),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("answer", sa.String(length=64), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"] ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_exercises_category_id"), "exercises", ["category_id"], unique=False)
    op.create_index(op.f("ix_exercises_group_id"), "exercises", ["group_id"], unique=False)
    op.create_index(op.f("ix_exercises_id"), "exercises", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=True),
        sa.Column("full_name", sa.String(length=64), nullable=False),
        sa.Column("current_exercise_id", sa.Integer(), nullable=True),
        sa.Column("exercise_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["current_exercise_id"], ["exercises.id"] ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "user_answers",
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("user_response", sa.String(length=256), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["exercise_id"], ["exercises.id"] ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"] ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_answers_exercise_id"), "user_answers", ["exercise_id"], unique=False)
    op.create_index(op.f("ix_user_answers_id"), "user_answers", ["id"], unique=False)
    op.create_index(op.f("ix_user_answers_user_id"), "user_answers", ["user_id"], unique=False)
    op.create_index("ix_user_answers_user_id_created_at", "user_answers", ["user_id", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_answers_user_id_created_at", table_name="user_answers")
    op.drop_index(op.f("ix_user_answers_user_id"), table_name="user_answers")
    op.drop_index(op.f("ix_user_answers_id"), table_name="user_answers")
    op.drop_index(op.f("ix_user_answers_exercise_id"), table_name="user_answers")
    op.drop_table("user_answers")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_exercises_id"), table_name="exercises")
    op.drop_index(op.f("ix_exercises_group_id"), table_name="exercises")
    op.drop_index(op.f("ix_exercises_category_id"), table_name="exercises")
    op.drop_table("exercises")
    op.drop_index(op.f("ix_categories_parent_id"), table_name="categories")
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
