"""
add user task config

Revision ID: 5657c99d2b3c
Revises: 311e459e8905
Create Date: 2026-02-08 08:19:45.736730

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5657c99d2b3c"
down_revision: str | Sequence[str] | None = "311e459e8905"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("current_task_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "current_task_config")
    # ### end Alembic commands ###
