"""
add group_id to user_answers

Revision ID: 6e29df240b36
Revises: bcb5a296c081
Create Date: 2026-02-08 18:12:19.438590

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6e29df240b36"
down_revision: str | Sequence[str] | None = "bcb5a296c081"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_answers", sa.Column("group_id", sa.UUID(), nullable=True))
    op.create_index(op.f("ix_user_answers_group_id"), "user_answers", ["group_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_answers_group_id"), table_name="user_answers")
    op.drop_column("user_answers", "group_id")
    # ### end Alembic commands ###
