"""
big answer

Revision ID: a92611f90877
Revises: 28e5c5539122
Create Date: 2026-03-29 17:25:24.066068

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a92611f90877"
down_revision: str | Sequence[str] | None = "28e5c5539122"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("exercises", "answer",
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("exercises", "answer",
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
