"""
enhance categories

Revision ID: bcb5a296c081
Revises: 5657c99d2b3c
Create Date: 2026-02-08 14:49:44.328598

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "bcb5a296c081"
down_revision: str | Sequence[str] | None = "5657c99d2b3c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("categories", "handler_type",
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.add_column("user_answers", sa.Column("category_id", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_user_answers_category_id"), "user_answers", ["category_id"], unique=False)
    op.create_foreign_key(None, "user_answers", "categories", ["category_id"], ["id"])
    op.add_column("users", sa.Column("current_category_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_users_current_category_id"), "users", ["current_category_id"], unique=False)
    op.create_foreign_key(None, "users", "categories", ["current_category_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_current_category_id_fkey", "users", type_="foreignkey")
    op.drop_index(op.f("ix_users_current_category_id"), table_name="users")
    op.drop_column("users", "current_category_id")
    op.drop_constraint("user_answers_category_id_fkey", "user_answers", type_="foreignkey")
    op.drop_index(op.f("ix_user_answers_category_id"), table_name="user_answers")
    op.drop_column("user_answers", "category_id")
    op.alter_column("categories", "handler_type",
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    # ### end Alembic commands ###
