"""
increase answer column length

Revision ID: e1b118af820c
Revises: 6e29df240b36
Create Date: 2026-02-13 11:47:05.423413

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e1b118af820c"
down_revision: str | Sequence[str] | None = "6e29df240b36"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("exercises", "answer",
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("exercises", "answer",
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###
